### ISSUE TITLE
It does not work for me

### ISSUE THREAD

**Issue by siabar** [lufte/python-telegram-bot-openshift#2]
Hi, When I set webhook in :
 if __name__ == '__main__':
    setup(webhook_url)

When i send a msg to my bot i do not receive any message from the bot. 
but when I run it without webhook it works fine. 

I did not change anything only change my webhook on openshift and my token from telegram.

Can you help me what is the problem?

**Comment by siabar** [comment]
And in webhook mode i also getting this warning:

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/telegram/ext/messagehandler.py:76: UserWarning: Using a list of filters in MessageHandler is getting deprecated, please use bitwise operators (& and |) instead. More info: https://git.io/vPTbc.
  warnings.warn('Using a list of filters in MessageHandler is getting '

**Comment by lufte** [comment]
```
if name == 'main':
    setup(webhook_url)
```
You shouldn't do this. I put comments on the parts of the code you need to change. If you still run into problems you should check the logs on your openshift app.

The other warning is related to the `python-telegram-bot` library and is understandable, as I wrote this code a few months ago but that library will keep upgrading and probably introducing backward incompatible changes from time to time.

**Comment by siabar** [comment]
I've started to learn recently, so my knowledge is not very high yet , but except that warning, there is not any other information or error on the logs.

**Comment by lufte** [comment]
Contact me on telegram with this same username and I'll give you a hand.
